queue_rules:
  - name: default
    merge_conditions:
      - check-success=ci
pull_request_rules:
  - name: queueable
    conditions:
      - base=cbtest-base
      - label=autoq
    actions:
      queue:
        name: default
